fun printInfo(country: String, capital: String, river: String) {
    println("$country - Capital: $capital, River: $river")
}

fun estonia() = printInfo("Estonia", "Tallinn", "Pärnu River")
fun latvia() = printInfo("Latvia", "Riga", "Daugava River")
fun lithuania() = printInfo("Lithuania", "Vilnius", "Neris River")
fun switzerland() = printInfo("Switzerland", "Bern", "Rhine River")
fun india() = printInfo("India", "New Delhi", "Ganga River")
fun korea() = printInfo("Korea (South)", "Seoul", "Han River")
fun japan() = printInfo("Japan", "Tokyo", "Shinano River")
fun china() = printInfo("China", "Beijing", "Yangtze River")
fun usa() = printInfo("USA", "Washington, D.C.", "Mississippi River")
fun belgium() = printInfo("Belgium", "Brussels", "Meuse River")

fun main() {
    estonia()
    println()
    latvia()
    println()
    lithuania()
    println()
    switzerland()
    println()
    india()
    println()
    korea()
    println()
    japan()
    println()
    china()
    println()
    usa()
    println()
    belgium()
}
